package myteam
 
import myteam.Counter
 
rule "Counter shower 1" 
    when $Counter  : Counter() 
 then 
    System.out.println("Counter there (1) : " + $Counter.getCount() + " and the name is : " + $Counter.getName());
 end

 rule "Counter shower 2" 
when 
    $Counter  : Counter()  
    accumulate (Counter() ; $cnt : count())
then 
    System.out.println("Counter there (2) : " + $Counter.getCount() + " and the name is : " + $Counter.getName()
    +" accumaulated value is " +$cnt);
end 

rule "Counter shower 3" 
when 
    Counter()  
then 
System.out.println("Counters there (3) : ");
end